sonar.projectKey=vidhipatel32_8.2CDevSecOps
sonar.organization=vidhipatel32
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
